import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiSearch, FiPlus, FiDownload, FiEye } from "react-icons/fi";

import Sidebar from "../../components/common/Sidebar";
import Navbar from "../../components/common/Navbar";
import Loader from "../../components/common/Loader";
import { getAllReports } from "../../services/reportService";

function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      const data = await getAllReports();
      setReports(data || []);
    } catch (error) {
      console.log(error);
      setReports([]);
    } finally {
      setLoading(false);
    }
  };

  const filteredReports = reports.filter(report => 
    report.reportName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    report.reportType?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div style={{ display: "flex", minHeight: "100vh" }}>
      <Sidebar />

      <div style={{ flex: 1, display: "flex", flexDirection: "column" }}>
        <Navbar />

        <div style={{ padding: "30px", flex: 1 }} className="animate-fade-in">
          {/* Header */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px" }}>
            <div>
              <h2 style={{ fontSize: "1.8rem", fontWeight: "700" }}>Reports</h2>
            </div>
          </div>

          {/* Search and Action Bar */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "20px", marginBottom: "20px" }}>
            <div style={{ position: "relative", width: "300px" }}>
              <FiSearch style={{ position: "absolute", left: "12px", top: "50%", transform: "translateY(-50%)", color: "var(--text-muted)" }} />
              <input
                type="text"
                placeholder="Search reports..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="form-input"
                style={{ paddingLeft: "36px", height: "40px" }}
              />
            </div>

            <Link to="/admin/generate-report" className="btn-primary" style={{ height: "40px" }}>
              <FiPlus /> Generate Report
            </Link>
          </div>

          {/* Table Container */}
          <div className="table-container">
            {loading ? (
              <div style={{ padding: "40px", textAlign: "center" }}><Loader /></div>
            ) : filteredReports.length === 0 ? (
              <div style={{ padding: "45px", textAlign: "center", color: "var(--text-muted)" }}>
                No reports found.
              </div>
            ) : (
              <table className="premium-table">
                <thead>
                  <tr>
                    <th>Report Name</th>
                    <th>Type</th>
                    <th>Generated On</th>
                    <th>Generated By</th>
                    <th style={{ textAlign: "center" }}>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredReports.map((report) => (
                    <tr key={report.reportId}>
                      <td style={{ fontWeight: "600", color: "var(--text-main)" }}>{report.reportName}</td>
                      <td>{report.reportType}</td>
                      <td>{report.generatedDate || "01 Jun 2024"}</td>
                      <td>{report.vendor?.companyName || "Admin User"}</td>
                      <td style={{ textAlign: "center" }}>
                        <div style={{ display: "flex", gap: "10px", justifyContent: "center" }}>
                          <a 
                            href={`http://localhost:8080/api/reports/download/${report.reportId}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{ color: "var(--text-muted)" }}
                          >
                            <FiDownload size={16} />
                          </a>
                          <a 
                            href={`http://localhost:8080/api/reports/view/${report.reportId}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{ color: "var(--text-muted)" }}
                          >
                            <FiEye size={16} />
                          </a>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export default Reports;